### ISSUE TITLE
Filter orcid lists so only publications are included

### ISSUE THREAD

**Issue by jbisits** [Climate-Data-Dynamics/climate-data-dynamics-lab-website#16]
Maybe filter based on DOI? Or based on name of journal? Not sure if either will work but something to filter could be placed in `cite.py` around here

```python
    # ensure date in proper format for correct date sorting
    if citation.get("date", ""):
        citation["date"] = format_date(citation.get("date", ""))

    # add new citation to list
    citations.append(citation)
```

so that only journal publications are included. Could also have a look at others who have used this template as they may have done something similar. Importantly we do not want this to be something that needs to be updated.

**Comment by taimoorsohail** [comment]
Do we know what the relevant columns for `citation` are? Is it a Pandas dataframe? If so, we could use Pandas indexing to remove specific journals. Unfortunately this will need updating as new members join, etc.

**Comment by jbisits** [comment]
The `citation` variable is a list

```python
# list of new citations
citations = []
```

so my thought was to get the names of all the journals (manually and this would require some upkeep but hopefully not very much) then remove any entry to the `citations` list where the journal entry is not from one of the manually set journal names. Might look something like

```python
# from line 149 in _cite/cite.py
    # add new citation to list
    citations.append(citation)

journals = # the journal list
for citation in citations
  if citations.journal notin journals
  # remove the citation
```

Then we would have a filtered `citations` variable which should only have journal articles (sorry about my lack of knowing python commands in the above snippet!). There might be better ways to do this but I think (or hope..) that this should be a set and forget solution apart from maybe needing to add a journal every now and then.

**Comment by jbisits** [comment]
I suppose you could convert `citations` to a pandas data frame if that is more straightforward though!

**Comment by jbisits** [comment]
Looking at this a bit more I think the fix would be something like

```python
journals = # the journal list
for idx, citation in enumerate(citations)
  if citations["publisher"] not in journals
  citations.remove(idx) # remove the citation
```

Will try this out in a PR when I get a moment.
