### ISSUE TITLE
Check the citation list works (probably use Jan's ORCID as he will be on all papers)

### ISSUE THREAD

**Issue by jbisits** [Climate-Data-Dynamics/climate-data-dynamics-lab-website#3]

**Comment by taimoorsohail** [comment]
We could set up a dedicated Google Scholar profile for the group, like this one that CFP at ANU has set up: https://scholar.google.com/citations?hl=en&user=H0Y8DBAAAAAJ&view_op=list_works&authuser=1&sortby=pubdate

**Comment by jbisits** [comment]
I tested this with my ORCID ID and it works. I actually wanted to see if the automatic PR `update_citations` the repo generates worked and it did first go! Just have to decide if group google scholar thing is best or if there is some other way to get all the citations.

**Comment by jbisits** [comment]
I did add a duplicate though (I think there is one on my ORCID) so need to make sure there is only one source on ORCID by the looks of things.

**Comment by jbisits** [comment]
Still an issue with @rohitsrb2020 ORCID id and not sure how to only include publications (not conference presentations for example).
